bot.py 2023-12-12 17:40:14,357 INFO Бот выполнил запрос. Ошибка: "None"
dispatcher.py 2023-12-12 17:40:14,370 INFO Start polling
dispatcher.py 2023-12-12 17:40:14,692 INFO Run polling for bot @some_test_123_bot id=5761144747 - 'testbot'
dispatcher.py 2023-12-12 17:40:14,745 INFO Polling stopped
dispatcher.py 2023-12-12 17:40:14,746 INFO Polling stopped for bot @some_test_123_bot id=5761144747 - 'testbot'
bot.py 2023-12-12 17:40:20,837 INFO Бот выполнил запрос. Ошибка: "None"
dispatcher.py 2023-12-12 17:40:20,850 INFO Start polling
dispatcher.py 2023-12-12 17:40:21,774 INFO Run polling for bot @some_test_123_bot id=5761144747 - 'testbot'
bot.py 2023-12-12 17:40:21,887 INFO Боту пришло сообщение: "EUR RUR от Артем"
bot.py 2023-12-12 17:40:21,889 INFO Боту пришло сообщение: "USD RUR от Артем"
bot.py 2023-12-12 17:40:21,890 INFO Боту пришло сообщение: "EUR RUR от Артем"
bot.py 2023-12-12 17:40:22,208 INFO Бот ответил: "1 USD = 90.22 RUR по курсу ЦБ"
dispatcher.py 2023-12-12 17:40:22,208 INFO Update id=533967872 is handled. Duration 328 ms by bot id=5761144747
bot.py 2023-12-12 17:40:22,231 INFO Бот ответил: "1 EUR = 97.4 RUR по курсу ЦБ"
dispatcher.py 2023-12-12 17:40:22,231 INFO Update id=533967871 is handled. Duration 344 ms by bot id=5761144747
bot.py 2023-12-12 17:40:22,310 INFO Бот ответил: "1 EUR = 97.4 RUR по курсу ЦБ"
dispatcher.py 2023-12-12 17:40:22,310 INFO Update id=533967873 is handled. Duration 422 ms by bot id=5761144747
bot.py 2023-12-12 17:40:25,600 INFO Боту пришло сообщение: "EUR RUR от Артем"
bot.py 2023-12-12 17:40:25,812 INFO Бот ответил: "1 EUR = 97.4 RUR по курсу ЦБ"
dispatcher.py 2023-12-12 17:40:25,813 INFO Update id=533967874 is handled. Duration 202 ms by bot id=5761144747
bot.py 2023-12-12 17:40:32,365 INFO Боту пришло сообщение: "выа ыавп от Артем"
core.py 2023-12-12 17:40:32,365 ERROR Неизвестная валюта ыавп
bot.py 2023-12-12 17:40:32,527 INFO Бот ответил: "Неизвестная валюта ыавп"
dispatcher.py 2023-12-12 17:40:32,527 INFO Update id=533967875 is handled. Duration 157 ms by bot id=5761144747
bot.py 2023-12-12 17:40:46,337 INFO Боту пришло сообщение: "140 41, от Артем"
core.py 2023-12-12 17:40:46,337 ERROR Неизвестная валюта 140
bot.py 2023-12-12 17:40:46,623 INFO Бот ответил: "Неизвестная валюта 140"
dispatcher.py 2023-12-12 17:40:46,623 INFO Update id=533967876 is handled. Duration 280 ms by bot id=5761144747
bot.py 2023-12-12 17:41:06,894 INFO Боту пришло сообщение: "usb mol от Артем"
core.py 2023-12-12 17:41:06,894 ERROR Неизвестная валюта USB
dispatcher.py 2023-12-12 17:41:06,894 INFO Update id=533967877 is not handled. Duration 16 ms by bot id=5761144747
dispatcher.py 2023-12-12 17:41:06,894 ERROR Cause exception while process update id=533967877 by bot id=5761144747
UnboundLocalError: cannot access local variable 'nominal' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\bot.py", line 94, in message_handler
    currency1_rate, wrong_input, nominal1 = UserInputCheck.second_check(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\core.py", line 108, in second_check
    return current_rate, wrong_input, nominal
                                      ^^^^^^^
UnboundLocalError: cannot access local variable 'nominal' where it is not associated with a value
bot.py 2023-12-12 17:41:12,880 INFO Боту пришло сообщение: "wcw wcw от Артем"
core.py 2023-12-12 17:41:12,880 ERROR Запрос остановлен. Выбраны одинаковые валюты для перевода WCW
bot.py 2023-12-12 17:41:13,188 INFO Бот ответил: "Запрос остановлен. Выбраны одинаковые валюты для перевода WCW"
dispatcher.py 2023-12-12 17:41:13,188 INFO Update id=533967878 is handled. Duration 297 ms by bot id=5761144747
bot.py 2023-12-12 17:41:20,151 INFO Боту пришло сообщение: "wec wwe от Артем"
core.py 2023-12-12 17:41:20,151 ERROR Неизвестная валюта WEC
dispatcher.py 2023-12-12 17:41:20,151 INFO Update id=533967879 is not handled. Duration 0 ms by bot id=5761144747
dispatcher.py 2023-12-12 17:41:20,151 ERROR Cause exception while process update id=533967879 by bot id=5761144747
UnboundLocalError: cannot access local variable 'nominal' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\bot.py", line 94, in message_handler
    currency1_rate, wrong_input, nominal1 = UserInputCheck.second_check(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\core.py", line 108, in second_check
    return current_rate, wrong_input, nominal
                                      ^^^^^^^
UnboundLocalError: cannot access local variable 'nominal' where it is not associated with a value
bot.py 2023-12-12 17:54:17,865 INFO Боту пришло сообщение: "USD TRY от Артем"
bot.py 2023-12-12 17:54:18,371 INFO Бот ответил: "1 USD = 28.97 TRY по курсу ЦБ"
dispatcher.py 2023-12-12 17:54:18,371 INFO Update id=533967880 is handled. Duration 500 ms by bot id=5761144747
bot.py 2023-12-12 17:54:23,602 INFO Боту пришло сообщение: "укук укук от Артем"
core.py 2023-12-12 17:54:23,602 ERROR Неизвестная валюта укук
bot.py 2023-12-12 17:54:23,833 INFO Бот ответил: "Неизвестная валюта укук"
dispatcher.py 2023-12-12 17:54:23,833 INFO Update id=533967881 is handled. Duration 233 ms by bot id=5761144747
bot.py 2023-12-12 17:54:28,713 INFO Боту пришло сообщение: "укк укк от Артем"
core.py 2023-12-12 17:54:28,713 ERROR Запрос остановлен. Выбраны одинаковые валюты для перевода УКК
bot.py 2023-12-12 17:54:29,005 INFO Бот ответил: "Запрос остановлен. Выбраны одинаковые валюты для перевода УКК"
dispatcher.py 2023-12-12 17:54:29,005 INFO Update id=533967882 is handled. Duration 296 ms by bot id=5761144747
bot.py 2023-12-12 17:54:35,494 INFO Боту пришло сообщение: "укк уук от Артем"
core.py 2023-12-12 17:54:35,495 ERROR Неизвестная валюта УКК
dispatcher.py 2023-12-12 17:54:35,495 INFO Update id=533967883 is not handled. Duration 0 ms by bot id=5761144747
dispatcher.py 2023-12-12 17:54:35,495 ERROR Cause exception while process update id=533967883 by bot id=5761144747
UnboundLocalError: cannot access local variable 'nominal' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\bot.py", line 94, in message_handler
    currency1_rate, wrong_input, nominal1 = UserInputCheck.second_check(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\core.py", line 108, in second_check
    return current_rate, wrong_input, nominal
                                      ^^^^^^^
UnboundLocalError: cannot access local variable 'nominal' where it is not associated with a value
bot.py 2023-12-12 17:56:28,818 INFO Боту пришло сообщение: "USD RUR от Артем"
bot.py 2023-12-12 17:56:29,253 INFO Бот ответил: "1 USD = 90.22 RUR по курсу ЦБ"
dispatcher.py 2023-12-12 17:56:29,253 INFO Update id=533967884 is handled. Duration 420 ms by bot id=5761144747
bot.py 2023-12-12 17:56:55,271 INFO Боту пришло сообщение: "врв врв от Артем"
core.py 2023-12-12 17:56:55,271 ERROR Запрос остановлен. Выбраны одинаковые валюты для перевода ВРВ
bot.py 2023-12-12 17:56:55,579 INFO Бот ответил: "Запрос остановлен. Выбраны одинаковые валюты для перевода ВРВ"
dispatcher.py 2023-12-12 17:56:55,579 INFO Update id=533967885 is handled. Duration 297 ms by bot id=5761144747
bot.py 2023-12-12 17:57:14,616 INFO Боту пришло сообщение: "ыпа ыка от Артем"
core.py 2023-12-12 17:57:14,616 ERROR Неизвестная валюта ЫПА
dispatcher.py 2023-12-12 17:57:14,617 INFO Update id=533967886 is not handled. Duration 0 ms by bot id=5761144747
dispatcher.py 2023-12-12 17:57:14,617 ERROR Cause exception while process update id=533967886 by bot id=5761144747
UnboundLocalError: cannot access local variable 'nominal' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\bot.py", line 94, in message_handler
    currency1_rate, wrong_input, nominal1 = UserInputCheck.second_check(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\core.py", line 108, in second_check
    return current_rate, wrong_input, nominal
                                      ^^^^^^^
UnboundLocalError: cannot access local variable 'nominal' where it is not associated with a value
dispatcher.py 2023-12-12 17:58:57,168 INFO Polling stopped
dispatcher.py 2023-12-12 17:58:57,169 INFO Polling stopped for bot @some_test_123_bot id=5761144747 - 'testbot'
bot.py 2023-12-12 17:59:04,199 INFO Бот выполнил запрос. Ошибка: "None"
dispatcher.py 2023-12-12 17:59:04,213 INFO Start polling
dispatcher.py 2023-12-12 17:59:04,474 INFO Run polling for bot @some_test_123_bot id=5761144747 - 'testbot'
bot.py 2023-12-12 17:59:12,008 INFO Боту пришло сообщение: "EUR RUR от Артем"
dispatcher.py 2023-12-12 17:59:12,008 INFO Update id=533967887 is not handled. Duration 0 ms by bot id=5761144747
dispatcher.py 2023-12-12 17:59:12,008 ERROR Cause exception while process update id=533967887 by bot id=5761144747
NameError: name 'здесь' is not defined
Traceback (most recent call last):
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\bot.py", line 94, in message_handler
    currency1_rate, wrong_input, nominal1 = UserInputCheck.second_check(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\currency_bot_async\core.py", line 102, in second_check
    nominal = current_table[current]['Nominal']   / здесь
                                                    ^^^^^
NameError: name 'здесь' is not defined
dispatcher.py 2023-12-12 17:59:42,277 INFO Polling stopped
dispatcher.py 2023-12-12 17:59:42,278 INFO Polling stopped for bot @some_test_123_bot id=5761144747 - 'testbot'
bot.py 2023-12-12 17:59:49,152 INFO Бот выполнил запрос. Ошибка: "None"
dispatcher.py 2023-12-12 17:59:49,165 INFO Start polling
dispatcher.py 2023-12-12 17:59:49,436 INFO Run polling for bot @some_test_123_bot id=5761144747 - 'testbot'
bot.py 2023-12-12 17:59:56,570 INFO Боту пришло сообщение: "EUR RUR от Артем"
bot.py 2023-12-12 17:59:57,066 INFO Бот ответил: "1 EUR = 97.4 RUR по курсу ЦБ"
dispatcher.py 2023-12-12 17:59:57,066 INFO Update id=533967888 is handled. Duration 500 ms by bot id=5761144747
bot.py 2023-12-12 17:59:57,884 INFO Боту пришло сообщение: "EUR RUR от Артем"
bot.py 2023-12-12 17:59:58,039 INFO Бот ответил: "1 EUR = 97.4 RUR по курсу ЦБ"
dispatcher.py 2023-12-12 17:59:58,039 INFO Update id=533967889 is handled. Duration 156 ms by bot id=5761144747
dispatcher.py 2023-12-12 18:06:21,382 INFO Polling stopped
dispatcher.py 2023-12-12 18:06:21,382 INFO Polling stopped for bot @some_test_123_bot id=5761144747 - 'testbot'
bot.py 2023-12-12 18:06:27,375 INFO Бот выполнил запрос. Ошибка: "None"
dispatcher.py 2023-12-12 18:06:27,390 INFO Start polling
dispatcher.py 2023-12-12 18:06:27,627 INFO Run polling for bot @some_test_123_bot id=5761144747 - 'testbot'
bot.py 2023-12-12 18:06:27,737 INFO Боту пришло сообщение: "EUR RUR от Артем"
bot.py 2023-12-12 18:06:28,212 INFO Бот ответил: "1 EUR = 97.4 RUR по курсу ЦБ"
dispatcher.py 2023-12-12 18:06:28,212 INFO Update id=533967890 is handled. Duration 483 ms by bot id=5761144747
bot.py 2023-12-12 18:06:33,691 INFO Боту пришло сообщение: "rth rwv от Артем"
core.py 2023-12-12 18:06:33,691 ERROR Неизвестная валюта RTH
bot.py 2023-12-12 18:06:33,899 INFO Бот ответил: "Неизвестная валюта RTH"
dispatcher.py 2023-12-12 18:06:33,900 INFO Update id=533967891 is handled. Duration 218 ms by bot id=5761144747
